development:
  adapter: postgresql
  encoding: unicode
  database: conquer_development

test: &test
  adapter: postgresql
  encoding: unicode
  database: conquer_test

production:
  adapter: postgresql
  encoding: unicode
  database: conquer_production
  pool: 5

cucumber:
  <<: *test
